inventory/urls.py
from django.urls import path
from .views import inventoryList, per_product_view, update, delete, add_product, dashboard

urlpatterns = [
    path("", inventoryList, name="inventorylist"),
    path("per_product_view/<int:pk>/", per_product_view, name="per_product"),
    path("product_update/<int:pk>/", update, name="product_update"),
    path("delete/<int:pk>/", delete, name="product_delete"),
    path("add/", add_product, name="product_add"),
    path("dashboard/", dashboard, name="dashboard"),
]

inventorySystem/urls.py
from os import name
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls, name="admin"),
    path("inventory/", include("inventory.urls")),
    path("", auth_views.LoginView.as_view(template_name = "inventory_system/login.html"), name="login"),
    path("logout/", auth_views.LogoutView.as_view(template_name = "inventory_system/logout.html"), name="logout"),
]

inventory/models.py
from django.db import models

class Inventory(models.Model):
    name = models.CharField(max_length =100, null=False, blank=False)
    cost_per_item = models.DecimalField(max_digits=19, decimal_places=2, null=False, blank=False)
    quantity_in_stock = models.IntegerField(null=False, blank=False)
    quantity_sold = models.IntegerField(null=False, blank=False)
    sales = models.DecimalField(max_digits=19, decimal_places=2, null=False, blank=False)
    stock_date = models.DateField(auto_now_add = True)
    last_sales_date = models.DateField(auto_now = True)

    def __str__(self) -> str:
        return self.name

inventory/forms.py
from django.forms import ModelForm
from .models import Inventory


class InventoryUpdateForm(ModelForm):
    class Meta:
        model = Inventory
        fields = ["name", "cost_per_item", "quantity_in_stock", "quantity_sold"]


class AddInventoryForm(ModelForm):
    class Meta:
        model = Inventory
        fields = ["name", "cost_per_item", "quantity_in_stock", "quantity_sold"]

inventory/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Inventory
#Update form import
from .forms import InventoryUpdateForm, AddInventoryForm
# flash messages
from django.contrib import messages
# dataframe
from django_pandas.io import read_frame
# plotly
import plotly
import plotly.express as px
# json
import json


@login_required()
def inventoryList(request):
    inventories = Inventory.objects.all()
    context = {
        "inventories": inventories
    }
    return render(request, "inventory/inventory_list.html", context=context)


@login_required()
def per_product_view(request, pk):
    inventory = get_object_or_404(Inventory, pk=pk)
    context = {
        'inventory': inventory
    }
    return render(request, "inventory/per_product.html", context=context)


@login_required()
def update(request, pk):
    inventory = get_object_or_404(Inventory, pk=pk)
    if request.method == "POST":
        updateForm = InventoryUpdateForm(data=request.POST)
        if updateForm.is_valid():
            inventory.name = updateForm.data['name']
            inventory.quantity_in_stock = updateForm.data['quantity_in_stock']
            inventory.quantity_sold = updateForm.data['quantity_sold']
            inventory.cost_per_item = updateForm.data['cost_per_item']
            inventory.sales = float(inventory.cost_per_item) * float(inventory.quantity_sold)
            inventory.save()
            messages.success(request, "Update Successful")
            return redirect(f"/inventory/per_product_view/{pk}/")
    else:
        updateForm = InventoryUpdateForm(instance=inventory)

    return render(request, "inventory/inventory_update.html", {'form' : updateForm})


@login_required()
def delete(request, pk):
    inventory = get_object_or_404(Inventory, pk=pk)
    inventory.delete()
    messages.success(request, "Inventory Deleted")
    return redirect("/inventory/")

    
    # messages.debug()
    # messages.info()
    # messages.success()
    # messages.warning()
    # messages.error()


@login_required()
def add_product(request):
    if request.method == "POST":
        updateForm = AddInventoryForm(data=request.POST)
        if updateForm.is_valid():
            new_invetory = updateForm.save(commit=False)
            new_invetory.sales = float(updateForm.data['cost_per_item']) * float(updateForm.data['quantity_sold'])
            new_invetory.save()
            messages.success(request, "Successfully Added Product")
            return redirect(f"/inventory/")
    else:
        updateForm = AddInventoryForm()

    return render(request, "inventory/inventory_add.html", {'form' : updateForm})


@login_required()
def dashboard(request):
    inventories = Inventory.objects.all()
    df = read_frame(inventories)
    
    # sales graph
    print(df.columns)
    sales_graph_df = df.groupby(by="last_sales_date", as_index=False, sort=False)['sales'].sum()
    print(sales_graph_df.sales)
    print(sales_graph_df.columns)
    sales_graph = px.line(sales_graph_df, x = sales_graph_df.last_sales_date, y = sales_graph_df.sales, title="Sales Trend")
    sales_graph = json.dumps(sales_graph, cls=plotly.utils.PlotlyJSONEncoder)

    
    # best performing product
    best_performing_product_df = df.groupby(by="name").sum().sort_values(by="quantity_sold")
    best_performing_product = px.bar(best_performing_product_df, 
                                    x = best_performing_product_df.index, 
                                    y = best_performing_product_df.quantity_sold, 
                                    title="Best Performing Product"
                                )
    best_performing_product = json.dumps(best_performing_product, cls=plotly.utils.PlotlyJSONEncoder)


    # best performing product in sales
    sales_graph_df_per_product_df = df.groupby(by="name", as_index=False, sort=False)['sales'].sum()
    best_performing_product_per_product = px.pie(sales_graph_df_per_product_df, 
                                    names = "name", 
                                    values = "sales", 
                                    title="Product Performance By Sales",
                                    # https://plotly.com/python/discrete-color/
                                    color_discrete_sequence=px.colors.qualitative.Bold,
                                )
    best_performing_product_per_product = json.dumps(best_performing_product_per_product, cls=plotly.utils.PlotlyJSONEncoder)


     # Most Product In Stock
    most_product_in_stock_df = df.groupby(by="name").sum().sort_values(by="quantity_in_stock")
    most_product_in_stock = px.pie(most_product_in_stock_df, 
                                    names = most_product_in_stock_df.index, 
                                    values = most_product_in_stock_df.quantity_in_stock, 
                                    title="Most Product In Stock"
                                )
    most_product_in_stock = json.dumps(most_product_in_stock, cls=plotly.utils.PlotlyJSONEncoder)

    context = {
        "sales_graph": sales_graph,
        "best_performing_product": best_performing_product,
        "most_product_in_stock": most_product_in_stock,
        "best_performing_product_per_product": best_performing_product_per_product
    }

    return render(request,"inventory/dashboard.html", context=context)

templates/inventory/dashboard.html
{% extends '../layout.html' %}
{% block content %}
  
  <div class="content-section">     
    <div class="row mx-auto justify-content-center">

      <div class="card m-4" style="width: 90%">
        <div class="card-body">
          <div id="chart1"></div>
        </div>
      </div>

      <div class="card m-4" style="width: 90%">
        <div class="card-body">
          <div id="chart2"></div>
        </div>
      </div>

      <div class="card m-4" style="width: 90%">
        <div class="card-body">
          <div id="chart3"></div>
        </div>
      </div>

      <div class="card m-4" style="width: 90%">
        <div class="card-body">
          <div id="chart4"></div>
        </div>
      </div>

  </div>
</div>

plotly CDN
<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
<script  type="text/javascript">
    var graph1 = {{ sales_graph | safe}};
    console.log("Graph 1 Data:", graph1);
    Plotly.plot("chart1", graph1,{});

    var graph2 = {{ best_performing_product | safe}};
    Plotly.plot("chart2", graph2,{});

    var graph3 = {{ most_product_in_stock | safe}};
    Plotly.plot("chart3", graph3,{});

    var graph4 = {{ best_performing_product_per_product | safe}};
    Plotly.plot("chart4", graph4,{});
</script>
{% endblock %}

templates/inventory/inventory_add.html
{% extends "../layout.html" %}
<!-- {% load crispy_forms_tags %}  -->
{% load static %}
{% block content %}
<div class="content-section">
    <!-- {{ form.media }} 
    <form method="POST">
        <fieldset>
            <legend class="border-bottom pb-2 mb-4 text-center">Inventory Add Form</legend>
            {% csrf_token %}
            <div class="form-group">
               
            </div>
            <div class="form-group pt-4">
                <button class="btn btn-outline-success" type="submit">Submit</button>
            </div>
      </fieldset>
    </form> -->
    <form method="POST" class="modern-form">
        {% csrf_token %}
        <h2 class="text-center mb-4">Inventory Add Form</h2>
        <div class="form-group">
            <label for="{{ form.name.id_for_label }}">Product Name</label>
            {{ form.name }}
        </div>
        <div class="form-group">
            <label for="{{ form.quantity_in_stock.id_for_label }}">Quantity in Stock</label>
            {{ form.quantity_in_stock }}
        </div>
        <div class="form-group">
            <label for="{{ form.quantity_sold.id_for_label }}">Quantity Sold</label>
            {{ form.quantity_sold }}
        </div>
        <div class="form-group">
            <label for="{{ form.cost_per_item.id_for_label }}">Cost per Item</label>
            {{ form.cost_per_item }}
        </div>
        <div class="form-group text-center">
            <button class="btn btn-success" type="submit">Submit</button>
        </div>
    </form>
</div>
{% endblock %}

templates/inventory/inventory_list.html
{% extends '../layout.html' %}
{% block content %}
<div class="content-section">
    <h1>Goodevening, Maureen </h1>
    <table class="table table-striped table-bordered table-hover">
        <thead class="thead-dark">
          <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Quantity In Stock</th>
            <th scope="col">Quantity Sold</th>
            <th scope="col">Cost Per Item</th>
            <th scope="col">Sales/Revenue</th>
            <th scope="col">Stock Date</th>
            <th scope="col">Last Sales Date</th>
          </tr>
        </thead>
        <tbody>
          {% for inventory in inventories %}
            <tr style='cursor: pointer; cursor: hand;' onclick="window.location=`{% url 'per_product' inventory.id %}`">
              <th scope="row">{{ forloop.counter }}</th>
              <th scope="col">{{ inventory.name }}</th>
              <th scope="col">{{ inventory.quantity_in_stock }}</th>
              <th scope="col">{{ inventory.quantity_sold }}</th>
              <th scope="col">{{ inventory.cost_per_item }}</th>
              <th scope="col">{{ inventory.sales }}</th>
              <th scope="col">{{ inventory.stock_date }}</th>
              <th scope="col">{{ inventory.last_sales_date }}</th>
            </tr>
          {% endfor %}
        </tbody>
    </table>
    <a class="nav-link" aria-current="page" href="{% url 'product_add' %}">
      <button class="btn btn-outline-success">Add New Product</button>
  </a>
</div>
{% endblock %}

templates/inventory/inventory_update.html
{% extends "../layout.html" %}
<!-- {% load crispy_forms_tags %}  -->
{% load static %}
{% block content %}
<div class="content-section">
    <!-- {{ form.media }} 
    <form method="POST">
        <fieldset>
            <legend class="border-bottom pb-2 mb-4 text-center">Inventory Update Form</legend>
            {% csrf_token %}
            <div class="form-group">
               
            </div>
            <div class="form-group pt-4">
                <button class="btn btn-outline-success" type="submit">Update</button>
            </div>
      </fieldset>
    </form> -->
    <h1 class="text-3xl mb-4">Update Product</h1>
    <form method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label for="id_name" class="form-label">Product Name</label>
            <input type="text" name="name" id="id_name" class="form-control" value="{{ form.name.value }}">
        </div>
        <div class="mb-3">
            <label for="id_quantity_in_stock" class="form-label">Quantity in Stock</label>
            <input type="number" name="quantity_in_stock" id="id_quantity_in_stock" class="form-control" value="{{ form.quantity_in_stock.value }}">
        </div>
        <div class="mb-3">
            <label for="id_quantity_sold" class="form-label">Quantity Sold</label>
            <input type="number" name="quantity_sold" id="id_quantity_sold" class="form-control" value="{{ form.quantity_sold.value }}">
        </div>
        <div class="mb-3">
            <label for="id_cost_per_item" class="form-label">Cost per Item</label>
            <input type="number" name="cost_per_item" id="id_cost_per_item" class="form-control" value="{{ form.cost_per_item.value }}">
        </div>
        <button type="submit" class="btn btn-primary">Update</button>
    </form>
</div>
{% endblock %}

templates/inventory/per_product.html
{% extends '../layout.html' %}
{% block content %}
  
  <div class="content-section">     
    <div class="row mx-auto justify-content-center">

      <div class="card m-4" style="width: 18rem;">
        <div class="card-body">
          <h5 class="card-title text-center">Product Name</h5>
          <div style="font-size: 30px;" class="text-center">
            <span><i class="fab fa-product-hunt"></i></span>
          </div>
          <h3 class="text-center">{{ inventory.name }}</h6>
        </div>
      </div>

      <div class="card m-4" style="width: 18rem;">
        <div class="card-body">
          <h5 class="card-title text-center">Quantity In Stock</h5>
          <div style="font-size: 30px;" class="text-center">
            <span><i class="fas fa-warehouse"></i></span>
          </div>
          <h3 class="text-center">{{ inventory.quantity_in_stock }}</h6>
        </div>
      </div>

      <div class="card m-4" style="width: 18rem;">
        <div class="card-body">
          <h5 class="card-title text-center">Quantity Sold</h5>
          <div style="font-size: 30px;" class="text-center">
            <span><i class="fas fa-warehouse"></i></span>
          </div>
          <h3 class="text-center">{{ inventory.quantity_sold }}</h6>
        </div>
      </div>

      <div class="card m-4" style="width: 18rem;">
        <div class="card-body">
          <h5 class="card-title text-center">Price Per {{ inventory.name }}</h5>
          <div style="font-size: 30px;" class="text-center">
            <span><i class="fas fa-dollar-sign"></i></span>
          </div>
          <h3 class="text-center">{{ inventory.cost_per_item }}</h6>
        </div>
      </div>

      <div class="card m-4" style="width: 18rem;">
        <div class="card-body">
          <h5 class="card-title text-center">Sales Or Revenue</h5>
          <div style="font-size: 30px;" class="text-center">
            <span><i class="fas fa-dollar-sign"></i></span>
          </div>
          <h3 class="text-center">{{ inventory.sales }}</h6>
        </div>
      </div>

      <div class="card m-4" style="width: 18rem;">
        <div class="card-body">
          <h5 class="card-title text-center">Stock Date</h5>
          <div style="font-size: 30px;" class="text-center">
            <span><i class="fas fa-calendar-alt"></i></span>
          </div>
          <h3 class="text-center">{{ inventory.stock_date }}</h6>
        </div>
      </div>

      <div class="card m-4" style="width: 18rem;">
        <div class="card-body">
          <h5 class="card-title text-center">Last Sales Date</h5>
          <div style="font-size: 30px;" class="text-center">
            <span><i class="fas fa-calendar-alt"></i></span>
          </div>
          <h3 class="text-center">{{ inventory.last_sales_date }}</h6>
        </div>
      </div>

      <a href="{% url 'product_update' inventory.id %}" class="btn btn-outline-success btn-sm mb-2">Update</a>
      <a href="{% url 'product_delete' inventory.id %}" class="btn btn-danger btn-sm mb-2">Delete</a>
  </div>
</div>
{% endblock %}

templates/inventory_system/login.html
{% extends "../layout.html" %}
{% load crispy_forms_tags %} 
{% load static %}
{% block content %}
<div class="content-section">
    <!-- {{ form.media }} 
    <form method="POST">
        <fieldset>
            <legend class="border-bottom pb-2 mb-4 text-center">Login Form</legend>
            {% csrf_token %}
            <div class="form-group">
                {{ form }}
            </div>
            <div class="form-group pt-4">
                <button class="btn btn-outline-success" type="submit">Login</button>
            </div>
      </fieldset>
    </form> -->
    <div class="login-container">
        <div class="image-container">
            
        </div>
        <div class="form-container flex flex-col justify-center align-center">
            <h1 class="text-7xl mb-16">Login</h1>
            <form method="post">
                {% csrf_token %}
                <div class="form-label mb-4 flex flex-col justify-center align-center">
                    <label for="id_username" class="text-lg">Username</label>
                    <input type="text" name="username" id="id_username" class="w-full p-2 border rounded">
                </div>
                <div class="mb-4">
                    <label for="id_password" class="text-lg">Password</label>
                    <input type="password" name="password" id="id_password" class="w-full p-2 border rounded">
                </div>
                <div class="btn-container flex items-center justify-between gap-12">
                    <button type="submit" class=" btn bg-red-500 text-green py-2 px-4 rounded border-green hover:bg-red-600">Login</button>
                    <a href="#" class="text-gray-500 hover:text-gray-700 mx-4px">Forgot Password?</a>
                </div>
            </form>
        </div>
    </div>
    
</div>
{% endblock %}

templates/inventory_system/logout.html
{% extends "../layout.html" %}
<!-- {% load crispy_forms_tags %}  -->
{% load static %}
{% block content %}
<div class="content-section">
    <small class="text-muted">
        You have been logged out. <a href="{% url 'login' %}">Login Again</a>
    </small>
</div>
{% endblock %}

templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/main.css' %}" type="text/css">

     <!-- fontawesome settings -->
    <link
     rel="stylesheet"
     href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0-2/css/all.min.css"
   />
    
    {% if title %}
        <title>{{ title }}</title>
    {% else %}
        <title>Oudees IMS</title>
    {% endif %}
</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'inventorylist' %}">Oudees IMS</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
              <a class="nav-link" aria-current="page" href="{% url 'inventorylist' %}">Home</a>
              {% if request.user.is_authenticated %}
                <a class="nav-link" aria-current="page" href="{% url 'inventorylist' %}">Inventory</a>
                <a class="nav-link" aria-current="page" href="{% url 'product_add' %}">Add Inventory</a>
                <a class="nav-link" aria-current="page" href="{% url 'dashboard' %}"><i class="fas fa-chart-line"> Dashboard</i></a>
                <a class="nav-link" aria-current="page" href="{% url 'admin:index' %}"><i class="fas fa-users-cog"> Admin</i></a>
                <form method="post" action="{% url 'logout' %}">
                  {% csrf_token %}
                  <button type="submit" class="nav-link btn"><i class="fas fa-sign-out-alt">Logout</i></button>
              </form>
              {% endif %}
            </div>
          </div>
        </div>
    </nav>

    <main>
        <div class="container-fluid">
         
          <div class="row">
            <div class="col-md-1"></div>
            <div class="col-md-10 col-sm-12 col-xm-12">
              {% if messages %} {% for message in messages %}
              <div class="alert alert-{{ message.tags }} mt-4">
                {{ message }}
              </div>
              {% endfor %} {% endif %} 
              {% block content %} {% endblock %}
            </div>
            <div class="col-md-1"></div>
          </div>
        </div>
    </main>
    

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
</body>
</html>